# This is a basic workflow to help you get started with Actions

name: Test Project

# Controls when the workflow will run
on: push
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-slim
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            second-action-react-jswebapp

      